import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const options = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: false, // 不生成 sourcemap 文件
	treeShaking: true,
	minify: prod, // 生产模式启用代码压缩
	outfile: 'main.js',
	loader: {
		'.css': 'text', // 将 .css 文件作为文本字符串导入（用于内置主题）
	},
	metafile: false, // 不生成 meta.json 文件
};

if (prod) {
	try {
		await esbuild.build(options);
	} catch (e) {
		console.error(e);
		process.exit(1);
	}
} else {
	try {
		const context = await esbuild.context(options);
		await context.watch();
	} catch (e) {
		console.error(e);
		process.exit(1);
	}
}
